---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: sept16-testplugins-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sept16-testplugins-1 
  name: sept16-testplugins-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi